### ISSUE TITLE
Python: Traceback

### ISSUE THREAD

**Issue by thezphynx** [nutti/blender-mqo#17]
[tiamat.zip](https://github.com/nutti/blender-mqo/files/9491473/tiamat.zip)
Python: Traceback (most recent call last):
  File "C:\Users\zphyn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_mqo\ops.py", line 861, in execute
    import_mqo_file(self.properties.filepath,
  File "C:\Users\zphyn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_mqo\ops.py", line 374, in import_mqo_file
    mqo_file.load(filepath)
  File "C:\Users\zphyn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_mqo\utils\mqo_file.py", line 1936, in load
    self._objects.append(self._parse_object(line))
  File "C:\Users\zphyn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_mqo\utils\mqo_file.py", line 1840, in _parse_object
    obj.add_faces(self._parse_face(line))
  File "C:\Users\zphyn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender_mqo\utils\mqo_file.py", line 1624, in _parse_face
    raise RuntimeError("Invalid format. (line:{})".format(first_line))
RuntimeError: Invalid format. (line:b'face 1865{')

location: <unknown location>:-1

**Comment by thezphynx** [comment]
Trying to import the attached .mqo and receiving this message. Please advise?

**Comment by nutti** [comment]
@thezphynx 

Thanks for your report. It seems the bug of this add-on.
I fixed it now, so you can try [the unstable version](https://github.com/nutti/blender-mqo/blob/master/docs/installation.md) which fixes this issue.
