### ISSUE TITLE
Blender3.4以降でエラーが発生

### ISSUE THREAD

**Issue by ho-mae** [nutti/blender-mqo#20]
System Information

OS: [Windows 10]
Blender version: [3.5]
Add-on version: [1.2]

Expected behavior
Blender3.4以降でインポートを行うと以下のエラーが発生いたします。

Description about the bug

Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_mqo\ops.py", line 861, in execute
    import_mqo_file(self.properties.filepath,
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_mqo\ops.py", line 380, in import_mqo_file
    materials_imported = import_materials(mqo_file, filepath,
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_mqo\ops.py", line 117, in import_materials
    materials_imported.append(import_material(mqo_mtrl, filepath,))
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_mqo\ops.py", line 106, in import_material
    return import_material_v280(mqo_mtrl, filepath)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender_mqo\ops.py", line 53, in import_material_v280
    output_node = new_mtrl.node_tree.nodes["Material Output"]
KeyError: 'bpy_prop_collection[key]: key "Material Output" not found'

対処方法をご教示ください。

**Comment by nutti** [comment]
@ho-mae 

プログラムのバグのようです。
修正しますので、少々お待ちください。

**Comment by nutti** [comment]
修正しました。
masterブランチから修正版を利用可能です。
近々、バージョン1.3をリリース予定のため、そちらを利用していただいても問題ありません。
