### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by barkin141** [nutti/blender-mqo#3]
**System Information**
  
* OS: [e.g. Windows]
* Blender version: [2.91]
* Add-on version: [1.0.0]

Python: Traceback (most recent call last):
  File "C:\Users\Barkin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_mqo\ops.py", line 690, in execute
    self.import_prefix if self.add_import_prefix else "")
  File "C:\Users\Barkin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_mqo\ops.py", line 339, in import_mqo_file
    materials_imported)
  File "C:\Users\Barkin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_mqo\ops.py", line 322, in import_objects
    objects_imported.append(import_object(mqo_obj, materials))
  File "C:\Users\Barkin\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blender_mqo\ops.py", line 170, in import_object
    bm_face = bm.faces.new(face_verts)
ValueError: faces.new(...): found the same (BMVert) used multiple times

location: <unknown location>:-1

Could you help me about this?

**Comment by nutti** [comment]
@barkin141 

Could you attach your .mqo file to this issue?
Then, I could investigate your issue.

**Comment by barkin141** [comment]
Of course,here 


[t-90.zip](https://github.com/nutti/blender-mqo/files/5756103/t-90.zip)

**Comment by nutti** [comment]
@barkin141 

Thanks! It helps me a lot.
I fixed this issue, and I confirmed that your issue was solved.

https://github.com/nutti/blender-mqo/archive/issue_3.zip

Could you try to test it?

**Comment by barkin141** [comment]
Thanks a lot @nutti 
Problem solved!

**Comment by nutti** [comment]
@barkin141 

Thanks for your help.
I merged the patch to master branch.
